### ISSUE TITLE
DictWithPWL unusable: the underlying C-library object has been freed.

### ISSUE THREAD

**Issue by codingjoe** [flashcode/msgcheck#4]
When I run something like
```shell
msgcheck -s str -d de,en --pwl spelling_wordlist/de $(MSGLANGS)
```
with `MSGLANGS` being multiple `.po`-files, I get the following error:

```text
Traceback (most recent call last):
  File "env/bin/msgcheck", line 11, in <module>
    sys.exit(main())
  File "env/lib/python3.6/site-packages/msgcheck/msgcheck.py", line 124, in main
    result = po_check.check_files(args.file)
  File "env/lib/python3.6/site-packages/msgcheck/po.py", line 523, in check_files
    result.append((po_file.filename, self.check_pofile(po_file)))
  File "env/lib/python3.6/site-packages/msgcheck/po.py", line 494, in check_pofile
    self.spelling, checker + self.extra_checkers)
  File "env/lib/python3.6/site-packages/msgcheck/po.py", line 276, in check_spelling
    for err in checkers[0]:
  File "env/lib/python3.6/site-packages/enchant/checker/__init__.py", line 230, in __next__
    return self.next()
  File "env/lib/python3.6/site-packages/enchant/checker/__init__.py", line 254, in next
    if self.dict.check(word):
  File "env/lib/python3.6/site-packages/enchant/__init__.py", line 869, in check
    if Dict.check(self,word):
  File "env/lib/python3.6/site-packages/enchant/__init__.py", line 646, in check
    self._check_this()
  File "env/lib/python3.6/site-packages/enchant/__init__.py", line 844, in _check_this
    Dict._check_this(self,msg)
  File "env/lib/python3.6/site-packages/enchant/__init__.py", line 618, in _check_this
    _EnchantObject._check_this(self,msg)
  File "env/lib/python3.6/site-packages/enchant/__init__.py", line 176, in _check_this
    raise Error(msg)
enchant.errors.Error: DictWithPWL unusable: the underlying C-library object has been freed.
make: *** [msgcheck] Error 1
```

**Comment by flashcode** [comment]
Hi,
I have no such error on my side with same arguments.
What's your version of python and python-enchant?

**Comment by codingjoe** [comment]
I can no longer reproduce it too. Sorry :/
